### ISSUE TITLE
Idea: Restructure the repo to include space for testing projects

### ISSUE THREAD

**Issue by AnnaSasDev** [NoMercy-Entertainment/NoMercyMediaServer-archive#5]
Currently, all project-related files and directories are placed at the root of the repository. To improve the organization and scalability of the project, I propose the following changes:

### Proposal:
- Move all project source code (e.g., NoMercy.Api, NoMercy.App, NoMercy.Data, etc.) into a new src folder.
- Create separate directories for:
  - tests for unit and integration tests.
  - tools for auxiliary scripts or automation (if applicable).
  - Any other directory needed for documentation or deployment configuration (docs, scripts, etc.).

This will help in keeping the project structure clean, especially as the codebase grows and additional elements (such as testing or tooling) are introduced.

### Suggested Directory Structure:
```bash
/.run
    /...
/src
    /NoMercy.Api
    /NoMercy.App
    /NoMercy.Data
    /NoMercy.Database
    /NoMercy.Encoder
    /NoMercy.Helpers
    /NoMercy.MediaProcessing
    /NoMercy.Networking
    /NoMercy.NmSystem
    /NoMercy.Providers
    /NoMercy.Queue
    /NoMercy.Server
    /...

/tests
    (Unit and integration test projects can go here)

/tools
    (Scripts or utilities for automation or building can go here)

/docs
    (Documentation files can go here)

NoMercy.Server.sln
... (all other root files as they exist now)    
```

**Comment by StoneyEagle** [comment]
Good idea!
